import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const customers=sqliteTable('customers',{userId:text('user_id').primaryKey(),name:text('name').notNull(),firstName:text('first_name').notNull().default(''),lastName:text('last_name').notNull().default(''),phone:text('phone').notNull(),email:text('email').notNull(),address:text('address').notNull(),accountType:text('account_type').notNull().default('buyer'),privacyVersion:text('privacy_version'),privacyAcceptedAt:integer('privacy_accepted_at'),wishlist:text('wishlist').notNull().default('[]')});
export const coinEvents=sqliteTable('coin_events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),delta:integer('delta').notNull(),reference:text('reference').notNull(),createdAt:integer('created_at').notNull()},t=>[index('coin_events_user_idx').on(t.userId)]);
export const faqFeedback=sqliteTable('faq_feedback',{id:text('id').primaryKey(),userId:text('user_id').notNull(),question:text('question').notNull(),resolved:integer('resolved').notNull(),updatedAt:integer('updated_at').notNull()});
export const identityChecks=sqliteTable('identity_checks',{userId:text('user_id').primaryKey(),kind:text('kind').notNull(),companyName:text('company_name').notNull().default(''),companyRcm:text('company_rcm').notNull().default(''),unregistered:integer('unregistered').notNull().default(0),sellerPlan:text('seller_plan').notNull().default('free'),courierPlan:text('courier_plan').notNull().default('standard'),documentType:text('document_type').notNull(),objectKey:text('object_key').notNull(),fileName:text('file_name').notNull(),status:text('status').notNull().default('pending'),note:text('note').notNull().default(''),submittedAt:integer('submitted_at').notNull(),reviewedAt:integer('reviewed_at')});
export const ownedStores=sqliteTable('owned_stores',{id:integer('id').primaryKey({autoIncrement:true}),userId:text('user_id').notNull(),name:text('name').notNull(),country:text('country').notNull()},t=>[index('owned_stores_user_idx').on(t.userId)]);
export const adminAccess=sqliteTable('admin_access',{id:text('id').primaryKey(),userId:text('user_id').notNull()});
export const deliveryScenarios=sqliteTable('delivery_scenarios',{userId:text('user_id').primaryKey(),snapshot:text('snapshot').notNull(),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull()});

export const sellerMessages=sqliteTable('seller_messages',{id:text('id').primaryKey(),sellerUserId:text('seller_user_id').notNull(),country:text('country').notNull(),sender:text('sender').notNull(),message:text('message').notNull(),createdAt:integer('created_at').notNull()},t=>[index('seller_messages_thread_idx').on(t.country,t.sellerUserId,t.createdAt)]);
export const courierMessages=sqliteTable('courier_messages',{id:text('id').primaryKey(),courierUserId:text('courier_user_id').notNull(),country:text('country').notNull(),sender:text('sender').notNull(),message:text('message').notNull(),createdAt:integer('created_at').notNull()},t=>[index('courier_messages_thread_idx').on(t.country,t.courierUserId,t.createdAt)]);
export const deliveryReviews=sqliteTable('delivery_reviews',{id:text('id').primaryKey(),buyerUserId:text('buyer_user_id').notNull(),courierUserId:text('courier_user_id'),country:text('country').notNull(),orderId:text('order_id').notNull(),sellerScores:text('seller_scores').notNull(),sellerNames:text('seller_names').notNull(),courierScore:integer('courier_score'),comment:text('comment').notNull().default(''),createdAt:integer('created_at').notNull()},t=>[index('delivery_reviews_country_idx').on(t.country,t.createdAt),index('delivery_reviews_courier_idx').on(t.courierUserId)]);

export const productPhotos=sqliteTable('product_photos',{id:text('id').primaryKey(),userId:text('user_id').notNull(),productId:integer('product_id').notNull(),sellerId:integer('seller_id').notNull(),objectKey:text('object_key').notNull(),contentType:text('content_type').notNull(),fileName:text('file_name').notNull(),createdAt:integer('created_at').notNull()},t=>[index('product_photos_user_product_idx').on(t.userId,t.productId)]);

export const marketProducts=sqliteTable('market_products',{key:text('key').primaryKey(),country:text('country').notNull(),productId:integer('product_id').notNull(),sellerId:integer('seller_id').notNull(),ownerUserId:text('owner_user_id').notNull(),data:text('data').notNull(),stock:integer('stock').notNull(),revision:integer('revision').notNull().default(1),updatedAt:integer('updated_at').notNull()},t=>[index('market_products_country_idx').on(t.country),index('market_products_owner_idx').on(t.ownerUserId)]);
export const marketOrders=sqliteTable('market_orders',{id:text('id').primaryKey(),country:text('country').notNull(),buyerUserId:text('buyer_user_id').notNull(),courierUserId:text('courier_user_id'),requestKey:text('request_key').notNull(),snapshot:text('snapshot').notNull(),revision:integer('revision').notNull().default(1),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('market_orders_country_idx').on(t.country,t.createdAt),uniqueIndex('market_orders_request_idx').on(t.requestKey)]);
export const marketParticipants=sqliteTable('market_participants',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),userId:text('user_id').notNull(),role:text('role').notNull(),sellerId:integer('seller_id').notNull().default(0)},t=>[index('market_participants_user_idx').on(t.userId,t.orderId),index('market_participants_order_idx').on(t.orderId)]);
export const marketMessages=sqliteTable('market_messages',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),senderUserId:text('sender_user_id').notNull(),senderRole:text('sender_role').notNull(),message:text('message').notNull(),createdAt:integer('created_at').notNull()},t=>[index('market_messages_order_idx').on(t.orderId,t.createdAt)]);
export const marketCouriers=sqliteTable('market_couriers',{userId:text('user_id').primaryKey(),country:text('country').notNull(),available:integer('available').notNull().default(0),payoutMethod:text('payout_method').notNull().default('mobile_money'),payoutAccount:text('payout_account').notNull().default(''),benefitsAccepted:integer('benefits_accepted').notNull().default(0)});
