import marketConfig from "../data/market-config.json" with { type: "json" };
export const seedCatalogue = [
  {
    id: 1,
    title: "Casque sans fil Essential",
    category: "High-tech",
    price: 85000,
    img: "headphones.png",
    tag: "Le son, en liberté",
    desc: "Un casque au design épuré pour accompagner votre quotidien. Modèle illustratif : les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    seller: 1,
    stock: 15,
    visible: true,
    approved: true,
    family: "Casques",
    images: ["headphones.png"],
  },
  {
    id: 2,
    title: "Baskets Urban Orange",
    category: "Mode",
    price: 65000,
    img: "sneakers.png",
    tag: "Votre touche de couleur",
    desc: "Des baskets au style urbain pour vos sorties en ville. Pointures, matière et disponibilité seront précisés lors de l’ouverture du catalogue réel.",
    seller: 3,
    stock: 15,
    visible: true,
    approved: true,
    family: "Baskets",
    images: ["sneakers.png"],
  },
  {
    id: 3,
    title: "Sac à main Daily",
    category: "Mode",
    price: 85500,
    img: "handbag.png",
    tag: "L’essentiel avec vous",
    desc: "Un sac au style intemporel pour garder vos essentiels à portée de main. Photo illustrative ; dimensions et matériaux à confirmer.",
    seller: 2,
    stock: 15,
    visible: true,
    approved: true,
    family: "Sacs",
    regularPrice: 95000,
    offer: { id: 3, discount: 10, kind: "daily" },
    images: ["handbag.png"],
  },
  {
    id: 4,
    title: "Casque Bluetooth Studio",
    category: "High-tech",
    price: 67150,
    seller: 1,
    img: "headphones.png",
    family: "Casques",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    regularPrice: 79000,
    offer: { id: 4, discount: 15, kind: "daily" },
    images: ["headphones.png"],
  },
  {
    id: 5,
    title: "Casque sans fil Essential",
    category: "High-tech",
    price: 82000,
    seller: 9,
    img: "headphones.png",
    family: "Casques",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["headphones.png"],
  },
  {
    id: 6,
    title: "Casque Bluetooth Studio",
    category: "High-tech",
    price: 92000,
    seller: 7,
    img: "headphones.png",
    family: "Casques",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["headphones.png"],
  },
  {
    id: 7,
    title: "Baskets Urban Orange",
    category: "Mode",
    price: 62000,
    seller: 2,
    img: "sneakers.png",
    family: "Baskets",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 8,
    title: "Baskets City Walk",
    category: "Mode",
    price: 72000,
    seller: 3,
    img: "sneakers.png",
    family: "Baskets",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 9,
    title: "Baskets City Walk",
    category: "Mode",
    price: 68000,
    seller: 6,
    img: "sneakers.png",
    family: "Baskets",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 10,
    title: "Sac à main Daily",
    category: "Mode",
    price: 89000,
    seller: 3,
    img: "handbag.png",
    family: "Sacs",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 11,
    title: "Sac à main Daily",
    category: "Mode",
    price: 98000,
    seller: 2,
    img: "handbag.png",
    family: "Sacs",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 12,
    title: "Sac week-end",
    category: "Mode",
    price: 115000,
    seller: 2,
    img: "handbag.png",
    family: "Sacs",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 13,
    title: "Service de table 12 pièces",
    category: "Maison",
    price: 75000,
    seller: 4,
    img: "product-dinner-set.jpg",
    family: "Table",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-dinner-set.jpg"],
  },
  {
    id: 14,
    title: "Assiettes 6 pièces",
    category: "Maison",
    price: 35000,
    seller: 4,
    img: "product-plates.jpg",
    family: "Table",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-plates.jpg"],
  },
  {
    id: 15,
    title: "Ventilateur sur pied",
    category: "Maison",
    price: 145000,
    seller: 7,
    img: "product-standing-fan.jpg",
    family: "Ventilation",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-standing-fan.jpg"],
  },
  {
    id: 16,
    title: "Ventilateur compact",
    category: "Maison",
    price: 95000,
    seller: 4,
    img: "product-desk-fan.jpg",
    family: "Ventilation",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-desk-fan.jpg"],
  },
  {
    id: 17,
    title: "Savon doux 3 pièces",
    category: "Beauté",
    price: 18000,
    seller: 5,
    img: "product-soap.jpg",
    family: "Soin",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-soap.jpg"],
  },
  {
    id: 18,
    title: "Lait de beauté 400 ml",
    category: "Beauté",
    price: 28000,
    seller: 5,
    img: "product-lotion.jpg",
    family: "Soin",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-lotion.jpg"],
  },
  {
    id: 19,
    title: "Coffret de jouets",
    category: "Enfants",
    price: 42000,
    seller: 6,
    img: "product-toys.jpg",
    family: "Jouets",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-toys.jpg"],
  },
  {
    id: 20,
    title: "Jeu éducatif",
    category: "Enfants",
    price: 32000,
    seller: 6,
    img: "product-puzzle.jpg",
    family: "Jouets",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-puzzle.jpg"],
  },
  {
    id: 21,
    title: "Riz 5 kg",
    category: "Épicerie",
    price: 25000,
    seller: 8,
    img: "product-rice.jpg",
    family: "Épicerie",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-rice.jpg"],
  },
  {
    id: 22,
    title: "Café 250 g",
    category: "Épicerie",
    price: 15000,
    seller: 8,
    img: "product-coffee.jpg",
    family: "Épicerie",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-coffee.jpg"],
  },
  {
    id: 23,
    title: "Ring light 26 cm",
    category: "Création",
    price: 65000,
    seller: 9,
    img: "product-ringlight.jpg",
    family: "Éclairage",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-ringlight.jpg"],
  },
  {
    id: 24,
    title: "Photo personnalisée encadrée",
    category: "Création",
    price: 45000,
    seller: 9,
    img: "product-frame.jpg",
    family: "Photo",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-frame.jpg"],
  },
  {
    id: 25,
    title: "Guitare acoustique",
    category: "Musique",
    price: 210000,
    seller: 10,
    img: "product-guitar.jpg",
    family: "Instruments",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-guitar.jpg"],
  },
  {
    id: 26,
    title: "Clavier musical",
    category: "Musique",
    price: 350000,
    seller: 10,
    img: "product-keyboard.jpg",
    family: "Instruments",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-keyboard.jpg"],
  },
  {
    id: 27,
    title: "Rallonge 5 prises",
    category: "Maison",
    price: 22000,
    seller: 7,
    img: "product-power-strip.jpg",
    family: "Électricité",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-power-strip.jpg"],
  },
  {
    id: 28,
    title: "Montre classique",
    category: "Mode",
    price: 55000,
    seller: 2,
    img: "product-watch.jpg",
    family: "Accessoires",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-watch.jpg"],
  },
  {
    id: 29,
    title: "Cravate élégante",
    category: "Mode",
    price: 20000,
    seller: 2,
    img: "product-tie.jpg",
    family: "Accessoires",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-tie.jpg"],
  },
  {
    id: 30,
    title: "Câble USB-C",
    category: "High-tech",
    price: 12000,
    seller: 1,
    img: "product-usb-c.jpg",
    family: "Câbles",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-usb-c.jpg"],
  },
  {
    id: 500,
    title: "Chemise homme classique",
    category: "Mode",
    price: 45000,
    seller: 2,
    family: "Chemises",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-shirt.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-shirt.jpg"],
  },
  {
    id: 501,
    title: "Robe femme quotidienne",
    category: "Mode",
    price: 68000,
    seller: 2,
    family: "Robes",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-dress.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-dress.jpg"],
  },
  {
    id: 502,
    title: "Veste homme habillée",
    category: "Mode",
    price: 120000,
    seller: 2,
    family: "Vestes",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-blazer.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-blazer.jpg"],
  },
  {
    id: 503,
    title: "Chaussures femme élégantes",
    category: "Mode",
    price: 72000,
    seller: 3,
    family: "Chaussures",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-womens-shoes.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-womens-shoes.jpg"],
  },
  {
    id: 504,
    title: "Accessoire femme foulard",
    category: "Mode",
    price: 18000,
    seller: 2,
    family: "Accessoires",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-scarf.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-scarf.jpg"],
  },
  {
    id: 505,
    title: "Habit enfant ensemble",
    category: "Enfants",
    price: 38000,
    seller: 6,
    family: "Habits",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-kids-outfit.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-kids-outfit.jpg"],
  },
  {
    id: 506,
    title: "Téléphone smartphone Essential",
    category: "High-tech",
    price: 320000,
    seller: 1,
    family: "Téléphones",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-smartphone.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-smartphone.jpg"],
  },
  {
    id: 507,
    title: "Ordinateur portable Bureau",
    category: "High-tech",
    price: 950000,
    seller: 1,
    family: "Informatique",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-laptop.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-laptop.jpg"],
  },
  {
    id: 508,
    title: "Cosmétique soin quotidien",
    category: "Beauté",
    price: 24000,
    seller: 5,
    family: "Soin",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-cosmetic.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-cosmetic.jpg"],
  },
];
export const seedShops = [
  {
    id: 1,
    name: "Kin Tech",
    domain: "Téléphones & informatique",
    city: "Kinshasa",
    commune: "Gombe",
    initials: "KT",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 2,
    name: "Élégance Congo",
    domain: "Vêtements & accessoires",
    city: "Kinshasa",
    commune: "Bandalungwa",
    initials: "EC",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 3,
    name: "Pas Urbain",
    domain: "Chaussures",
    city: "Kinshasa",
    commune: "Kalamu",
    initials: "PU",
    homeCountry: "CD",
    reviewed: false,
  },
  {
    id: 4,
    name: "Maison Lushi",
    domain: "Maison & arts de la table",
    city: "Lubumbashi",
    commune: "Lubumbashi",
    initials: "ML",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 5,
    name: "Belle au Naturel",
    domain: "Beauté & cosmétiques",
    city: "Kinshasa",
    commune: "Lemba",
    initials: "BN",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 6,
    name: "Petit Monde",
    domain: "Bébé & jouets",
    city: "Lubumbashi",
    commune: "Kenya",
    initials: "PM",
    homeCountry: "CD",
    reviewed: false,
  },
  {
    id: 7,
    name: "Électro Plus",
    domain: "Électroménager & ventilation",
    city: "Lubumbashi",
    commune: "Kampemba",
    initials: "EP",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 8,
    name: "Saveurs du Congo",
    domain: "Épicerie non périssable",
    city: "Kinshasa",
    commune: "Limete",
    initials: "SC",
    homeCountry: "CD",
    reviewed: true,
  },
  {
    id: 9,
    name: "Studio Créatif",
    domain: "Photo personnalisée & éclairage",
    city: "Kinshasa",
    commune: "Kintambo",
    initials: "ST",
    homeCountry: "CD",
    reviewed: false,
  },
  {
    id: 10,
    name: "Lushi Musique",
    domain: "Instruments de musique",
    city: "Lubumbashi",
    commune: "Katuba",
    initials: "LM",
    homeCountry: "CD",
    reviewed: true,
  },
];
export const deliveryTariffs = [
  [1, "Central", "Gombe", "Très accessible", "Very accessible", 10000],
  [1, "Central", "Kinshasa", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Barumbu", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Lingwala", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Kasa-Vubu", "Très accessible", "Very accessible", 8000],
  [2, "Ouest", "Kintambo", "Accessible", "Accessible", 10000],
  [2, "Ouest", "Ngaliema", "Accessible", "Accessible", 10000],
  [2, "Ouest", "Bandalungwa", "Accessible", "Accessible", 8000],
  [2, "Ouest", "Selembao", "Accessible", "Accessible", 7500],
  [3, "Sud", "Lemba", "Modérée", "Moderate", 8000],
  [3, "Sud", "Limete", "Modérée", "Moderate", 8000],
  [3, "Sud", "Matete", "Modérée", "Moderate", 7500],
  [3, "Sud", "Ngaba", "Modérée", "Moderate", 7500],
  [3, "Sud", "Makala", "Modérée", "Moderate", 7500],
  [3, "Sud", "Kisenso", "Modérée", "Moderate", 7000],
  [4, "Est", "N’Djili", "Éloignée", "Distant", 9000],
  [4, "Est", "Masina", "Éloignée", "Distant", 9000],
  [4, "Est", "Kimbanseke", "Éloignée", "Distant", 9500],
  [5, "Périphérie", "N’Sele", "Très éloignée", "Very distant", 12500],
  [5, "Périphérie", "Maluku", "Très éloignée", "Very distant", 15000],
  [5, "Périphérie", "Mont-Ngafula", "Très éloignée", "Very distant", 10000],
  [3, "Sud", "Bumbu", "À confirmer", "To confirm", 7500],
  [3, "Sud", "Kalamu", "À confirmer", "To confirm", 7500],
  [3, "Sud", "Ngiri-Ngiri", "À confirmer", "To confirm", 7500],
];
export const deliveryCommunes = {
  Kinshasa: [
    "Bandalungwa",
    "Barumbu",
    "Bumbu",
    "Gombe",
    "Kalamu",
    "Kasa-Vubu",
    "Kimbanseke",
    "Kinshasa",
    "Kintambo",
    "Kisenso",
    "Lemba",
    "Limete",
    "Lingwala",
    "Makala",
    "Maluku",
    "Masina",
    "Matete",
    "Mont-Ngafula",
    "Ndjili",
    "Ngaba",
    "Ngaliema",
    "Ngiri-Ngiri",
    "Nsele",
    "Selembao",
  ],
  Lubumbashi: [
    "Annexe",
    "Kamalondo",
    "Kampemba",
    "Katuba",
    "Kenya",
    "Lubumbashi",
    "Ruashi",
  ],
};
export const seedCatalogueCG = [
  {
    id: 1,
    title: "Casque sans fil Essential",
    category: "High-tech",
    price: 85000,
    img: "headphones.png",
    tag: "Le son, en liberté",
    desc: "Un casque au design épuré pour accompagner votre quotidien. Modèle illustratif : les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    seller: 101,
    stock: 15,
    visible: true,
    approved: true,
    family: "Casques",
    images: ["headphones.png"],
  },
  {
    id: 2,
    title: "Baskets Urban Orange",
    category: "Mode",
    price: 65000,
    img: "sneakers.png",
    tag: "Votre touche de couleur",
    desc: "Des baskets au style urbain pour vos sorties en ville. Pointures, matière et disponibilité seront précisés lors de l’ouverture du catalogue réel.",
    seller: 103,
    stock: 15,
    visible: true,
    approved: true,
    family: "Baskets",
    images: ["sneakers.png"],
  },
  {
    id: 3,
    title: "Sac à main Daily",
    category: "Mode",
    price: 85500,
    img: "handbag.png",
    tag: "L’essentiel avec vous",
    desc: "Un sac au style intemporel pour garder vos essentiels à portée de main. Photo illustrative ; dimensions et matériaux à confirmer.",
    seller: 102,
    stock: 15,
    visible: true,
    approved: true,
    family: "Sacs",
    regularPrice: 95000,
    offer: { id: 3, discount: 10, kind: "daily" },
    images: ["handbag.png"],
  },
  {
    id: 4,
    title: "Casque Bluetooth Studio",
    category: "High-tech",
    price: 67150,
    seller: 101,
    img: "headphones.png",
    family: "Casques",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    regularPrice: 79000,
    offer: { id: 4, discount: 15, kind: "daily" },
    images: ["headphones.png"],
  },
  {
    id: 5,
    title: "Casque sans fil Essential",
    category: "High-tech",
    price: 82000,
    seller: 109,
    img: "headphones.png",
    family: "Casques",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["headphones.png"],
  },
  {
    id: 6,
    title: "Casque Bluetooth Studio",
    category: "High-tech",
    price: 92000,
    seller: 107,
    img: "headphones.png",
    family: "Casques",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["headphones.png"],
  },
  {
    id: 7,
    title: "Baskets Urban Orange",
    category: "Mode",
    price: 62000,
    seller: 102,
    img: "sneakers.png",
    family: "Baskets",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 8,
    title: "Baskets City Walk",
    category: "Mode",
    price: 72000,
    seller: 103,
    img: "sneakers.png",
    family: "Baskets",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 9,
    title: "Baskets City Walk",
    category: "Mode",
    price: 68000,
    seller: 106,
    img: "sneakers.png",
    family: "Baskets",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["sneakers.png"],
  },
  {
    id: 10,
    title: "Sac à main Daily",
    category: "Mode",
    price: 89000,
    seller: 103,
    img: "handbag.png",
    family: "Sacs",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 11,
    title: "Sac à main Daily",
    category: "Mode",
    price: 98000,
    seller: 102,
    img: "handbag.png",
    family: "Sacs",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 12,
    title: "Sac week-end",
    category: "Mode",
    price: 115000,
    seller: 102,
    img: "handbag.png",
    family: "Sacs",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["handbag.png"],
  },
  {
    id: 13,
    title: "Service de table 12 pièces",
    category: "Maison",
    price: 75000,
    seller: 104,
    img: "product-dinner-set.jpg",
    family: "Table",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-dinner-set.jpg"],
  },
  {
    id: 14,
    title: "Assiettes 6 pièces",
    category: "Maison",
    price: 35000,
    seller: 104,
    img: "product-plates.jpg",
    family: "Table",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-plates.jpg"],
  },
  {
    id: 15,
    title: "Ventilateur sur pied",
    category: "Maison",
    price: 145000,
    seller: 107,
    img: "product-standing-fan.jpg",
    family: "Ventilation",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-standing-fan.jpg"],
  },
  {
    id: 16,
    title: "Ventilateur compact",
    category: "Maison",
    price: 95000,
    seller: 104,
    img: "product-desk-fan.jpg",
    family: "Ventilation",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-desk-fan.jpg"],
  },
  {
    id: 17,
    title: "Savon doux 3 pièces",
    category: "Beauté",
    price: 18000,
    seller: 105,
    img: "product-soap.jpg",
    family: "Soin",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-soap.jpg"],
  },
  {
    id: 18,
    title: "Lait de beauté 400 ml",
    category: "Beauté",
    price: 28000,
    seller: 105,
    img: "product-lotion.jpg",
    family: "Soin",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-lotion.jpg"],
  },
  {
    id: 19,
    title: "Coffret de jouets",
    category: "Enfants",
    price: 42000,
    seller: 106,
    img: "product-toys.jpg",
    family: "Jouets",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-toys.jpg"],
  },
  {
    id: 20,
    title: "Jeu éducatif",
    category: "Enfants",
    price: 32000,
    seller: 106,
    img: "product-puzzle.jpg",
    family: "Jouets",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-puzzle.jpg"],
  },
  {
    id: 21,
    title: "Riz 5 kg",
    category: "Épicerie",
    price: 25000,
    seller: 108,
    img: "product-rice.jpg",
    family: "Épicerie",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-rice.jpg"],
  },
  {
    id: 22,
    title: "Café 250 g",
    category: "Épicerie",
    price: 15000,
    seller: 108,
    img: "product-coffee.jpg",
    family: "Épicerie",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-coffee.jpg"],
  },
  {
    id: 23,
    title: "Ring light 26 cm",
    category: "Création",
    price: 65000,
    seller: 109,
    img: "product-ringlight.jpg",
    family: "Éclairage",
    stock: 13,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-ringlight.jpg"],
  },
  {
    id: 24,
    title: "Photo personnalisée encadrée",
    category: "Création",
    price: 45000,
    seller: 109,
    img: "product-frame.jpg",
    family: "Photo",
    stock: 14,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-frame.jpg"],
  },
  {
    id: 25,
    title: "Guitare acoustique",
    category: "Musique",
    price: 210000,
    seller: 110,
    img: "product-guitar.jpg",
    family: "Instruments",
    stock: 15,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-guitar.jpg"],
  },
  {
    id: 26,
    title: "Clavier musical",
    category: "Musique",
    price: 350000,
    seller: 110,
    img: "product-keyboard.jpg",
    family: "Instruments",
    stock: 16,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-keyboard.jpg"],
  },
  {
    id: 27,
    title: "Rallonge 5 prises",
    category: "Maison",
    price: 22000,
    seller: 107,
    img: "product-power-strip.jpg",
    family: "Électricité",
    stock: 17,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-power-strip.jpg"],
  },
  {
    id: 28,
    title: "Montre classique",
    category: "Mode",
    price: 55000,
    seller: 102,
    img: "product-watch.jpg",
    family: "Accessoires",
    stock: 10,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-watch.jpg"],
  },
  {
    id: 29,
    title: "Cravate élégante",
    category: "Mode",
    price: 20000,
    seller: 102,
    img: "product-tie.jpg",
    family: "Accessoires",
    stock: 11,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-tie.jpg"],
  },
  {
    id: 30,
    title: "Câble USB-C",
    category: "High-tech",
    price: 12000,
    seller: 101,
    img: "product-usb-c.jpg",
    family: "Câbles",
    stock: 12,
    visible: true,
    approved: true,
    tag: "Sélection locale",
    desc: "Article et prix illustratifs. Caractéristiques à confirmer auprès du vendeur avant le lancement.",
    images: ["product-usb-c.jpg"],
  },
  {
    id: 500,
    title: "Chemise homme classique",
    category: "Mode",
    price: 45000,
    seller: 102,
    family: "Chemises",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-shirt.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-shirt.jpg"],
  },
  {
    id: 501,
    title: "Robe femme quotidienne",
    category: "Mode",
    price: 68000,
    seller: 102,
    family: "Robes",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-dress.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-dress.jpg"],
  },
  {
    id: 502,
    title: "Veste homme habillée",
    category: "Mode",
    price: 120000,
    seller: 102,
    family: "Vestes",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-blazer.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-blazer.jpg"],
  },
  {
    id: 503,
    title: "Chaussures femme élégantes",
    category: "Mode",
    price: 72000,
    seller: 103,
    family: "Chaussures",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-womens-shoes.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-womens-shoes.jpg"],
  },
  {
    id: 504,
    title: "Accessoire femme foulard",
    category: "Mode",
    price: 18000,
    seller: 102,
    family: "Accessoires",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-scarf.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-scarf.jpg"],
  },
  {
    id: 505,
    title: "Habit enfant ensemble",
    category: "Enfants",
    price: 38000,
    seller: 106,
    family: "Habits",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-kids-outfit.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-kids-outfit.jpg"],
  },
  {
    id: 506,
    title: "Téléphone smartphone Essential",
    category: "High-tech",
    price: 320000,
    seller: 101,
    family: "Téléphones",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-smartphone.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-smartphone.jpg"],
  },
  {
    id: 507,
    title: "Ordinateur portable Bureau",
    category: "High-tech",
    price: 950000,
    seller: 101,
    family: "Informatique",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-laptop.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-laptop.jpg"],
  },
  {
    id: 508,
    title: "Cosmétique soin quotidien",
    category: "Beauté",
    price: 24000,
    seller: 105,
    family: "Soin",
    stock: 12,
    visible: true,
    approved: true,
    img: "product-cosmetic.jpg",
    tag: "Sélection locale",
    desc: "Produit et photo illustratifs pour explorer YAVIYA. Les caractéristiques et la disponibilité seront confirmées par le vendeur.",
    images: ["product-cosmetic.jpg"],
  },
];
export const seedShopsCG = [
  {
    id: 101,
    name: "Brazza Tech",
    domain: "Téléphones & informatique",
    city: "Brazzaville",
    commune: "Makélékélé",
    initials: "BT",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 102,
    name: "Atelier Moungali",
    domain: "Vêtements & accessoires",
    city: "Pointe-Noire",
    commune: "Mvoumvou",
    initials: "AM",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 103,
    name: "Ponton Sneakers",
    domain: "Chaussures",
    city: "Brazzaville",
    commune: "Poto-Poto",
    initials: "PS",
    homeCountry: "CG",
    reviewed: false,
  },
  {
    id: 104,
    name: "Maison Bacongo",
    domain: "Maison & arts de la table",
    city: "Pointe-Noire",
    commune: "Loandjili",
    initials: "MB",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 105,
    name: "Beauté Ouenzé",
    domain: "Beauté & cosmétiques",
    city: "Brazzaville",
    commune: "Ouenzé",
    initials: "BO",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 106,
    name: "Les Petits de Ponton",
    domain: "Bébé & jouets",
    city: "Pointe-Noire",
    commune: "Ngoyo",
    initials: "LP",
    homeCountry: "CG",
    reviewed: false,
  },
  {
    id: 107,
    name: "Électro Brazza",
    domain: "Électroménager & ventilation",
    city: "Brazzaville",
    commune: "Mfilou",
    initials: "ÉB",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 108,
    name: "Saveurs de Loandjili",
    domain: "Épicerie non périssable",
    city: "Pointe-Noire",
    commune: "Mvoumvou",
    initials: "Sd",
    homeCountry: "CG",
    reviewed: true,
  },
  {
    id: 109,
    name: "Studio Poto-Poto",
    domain: "Photo personnalisée & éclairage",
    city: "Brazzaville",
    commune: "Djiri",
    initials: "SP",
    homeCountry: "CG",
    reviewed: false,
  },
  {
    id: 110,
    name: "Ponton Musique",
    domain: "Instruments de musique",
    city: "Pointe-Noire",
    commune: "Loandjili",
    initials: "PM",
    homeCountry: "CG",
    reviewed: true,
  },
];
export const deliveryTariffsCG = [
  [1, "Central", "Gombe", "Très accessible", "Very accessible", 10000],
  [1, "Central", "Kinshasa", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Barumbu", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Lingwala", "Très accessible", "Very accessible", 8000],
  [1, "Central", "Kasa-Vubu", "Très accessible", "Very accessible", 8000],
  [2, "Ouest", "Kintambo", "Accessible", "Accessible", 10000],
  [2, "Ouest", "Ngaliema", "Accessible", "Accessible", 10000],
  [2, "Ouest", "Bandalungwa", "Accessible", "Accessible", 8000],
  [2, "Ouest", "Selembao", "Accessible", "Accessible", 7500],
  [3, "Sud", "Lemba", "Modérée", "Moderate", 8000],
  [3, "Sud", "Limete", "Modérée", "Moderate", 8000],
  [3, "Sud", "Matete", "Modérée", "Moderate", 7500],
  [3, "Sud", "Ngaba", "Modérée", "Moderate", 7500],
  [3, "Sud", "Makala", "Modérée", "Moderate", 7500],
  [3, "Sud", "Kisenso", "Modérée", "Moderate", 7000],
  [4, "Est", "N’Djili", "Éloignée", "Distant", 9000],
  [4, "Est", "Masina", "Éloignée", "Distant", 9000],
  [4, "Est", "Kimbanseke", "Éloignée", "Distant", 9500],
  [5, "Périphérie", "N’Sele", "Très éloignée", "Very distant", 12500],
  [5, "Périphérie", "Maluku", "Très éloignée", "Very distant", 15000],
  [5, "Périphérie", "Mont-Ngafula", "Très éloignée", "Very distant", 10000],
  [3, "Sud", "Bumbu", "À confirmer", "To confirm", 7500],
  [3, "Sud", "Kalamu", "À confirmer", "To confirm", 7500],
  [3, "Sud", "Ngiri-Ngiri", "À confirmer", "To confirm", 7500],
];
export const deliveryCommunesCG = {
  Brazzaville: [
    "Makélékélé",
    "Bacongo",
    "Poto-Poto",
    "Moungali",
    "Ouenzé",
    "Talangaï",
    "Mfilou",
    "Madibou",
    "Djiri",
  ],
  "Pointe-Noire": [
    "Lumumba",
    "Mvoumvou",
    "Tié-Tié",
    "Loandjili",
    "Mongo-Mpoukou",
    "Ngoyo",
  ],
};

// Only unchanged illustrative seed galleries receive generated alternate views.
for (const product of [...seedCatalogue, ...seedCatalogueCG]) {
  const gallery = marketConfig.productGalleries[product.img];
  if (gallery) product.images = [...gallery];
}
