-- Private compatibility schema used by the existing YAVIYA API while the
-- public marketplace model is migrated incrementally. It is deliberately not
-- exposed through the Supabase Data API.
create schema if not exists runtime;
revoke all on schema runtime from public, anon, authenticated;
grant usage on schema runtime to yaviya_runtime;

create or replace function runtime.json_extract(source text, path text)
returns text
language sql
immutable
strict
set search_path = pg_catalog
as $$
  select source::jsonb #>> string_to_array(trim(leading '.' from trim(leading '$' from path)), '.')
$$;

create table runtime.customers (
  user_id text primary key,
  name text not null,
  phone text not null,
  email text not null,
  address text not null,
  wishlist text not null default '[]',
  account_type text not null default 'buyer',
  privacy_version text,
  privacy_accepted_at bigint,
  first_name text not null default '',
  last_name text not null default '',
  country_code text not null default '',
  currency text not null default '',
  preferred_language text not null default 'fr'
);

create table runtime.coin_events (
  id text primary key, user_id text not null, kind text not null,
  delta integer not null, reference text not null, created_at bigint not null
);
create index coin_events_user_idx on runtime.coin_events(user_id);

create table runtime.faq_feedback (
  id text primary key, user_id text not null, question text not null,
  resolved integer not null, updated_at bigint not null
);

create table runtime.admin_access (id text primary key, user_id text not null);

create table runtime.identity_checks (
  user_id text primary key, kind text not null, company_name text not null default '',
  company_rcm text not null default '', document_type text not null,
  object_key text not null, file_name text not null, status text not null default 'pending',
  note text not null default '', submitted_at bigint not null, reviewed_at bigint,
  unregistered integer not null default 0, seller_plan text not null default 'free',
  courier_plan text not null default 'standard', issuing_country text not null default '',
  document_mime text not null default ''
);

create table runtime.owned_stores (
  id bigint generated by default as identity primary key,
  user_id text not null, name text not null, country text not null
);
create index owned_stores_user_idx on runtime.owned_stores(user_id);

create table runtime.delivery_scenarios (
  user_id text primary key, snapshot text not null,
  revision integer not null default 0, updated_at bigint not null
);

create table runtime.seller_messages (
  id text primary key, seller_user_id text not null, country text not null,
  sender text not null, message text not null, created_at bigint not null
);
create index seller_messages_thread_idx on runtime.seller_messages(country, seller_user_id, created_at);

create table runtime.courier_messages (
  id text primary key, courier_user_id text not null, country text not null,
  sender text not null, message text not null, created_at bigint not null
);
create index courier_messages_thread_idx on runtime.courier_messages(country, courier_user_id, created_at);

create table runtime.delivery_reviews (
  id text primary key, buyer_user_id text not null, courier_user_id text,
  country text not null, order_id text not null, seller_scores text not null,
  seller_names text not null, courier_score integer, comment text not null default '',
  created_at bigint not null
);
create index delivery_reviews_country_idx on runtime.delivery_reviews(country, created_at);
create index delivery_reviews_courier_idx on runtime.delivery_reviews(courier_user_id);

create table runtime.product_photos (
  id text primary key, user_id text not null, product_id integer not null,
  seller_id integer not null, object_key text not null, content_type text not null,
  file_name text not null, created_at bigint not null
);
create index product_photos_user_product_idx on runtime.product_photos(user_id, product_id);

create table runtime.market_couriers (
  user_id text primary key, country text not null, available integer not null default 0,
  payout_method text not null default 'mobile_money', payout_account text not null default '',
  benefits_accepted integer not null default 0
);

create table runtime.market_messages (
  id text primary key, order_id text not null, sender_user_id text not null,
  sender_role text not null, message text not null, created_at bigint not null
);
create index market_messages_order_idx on runtime.market_messages(order_id, created_at);

create table runtime.market_orders (
  id text primary key, country text not null, buyer_user_id text not null,
  courier_user_id text, request_key text not null unique, snapshot text not null,
  revision integer not null default 1, created_at bigint not null, updated_at bigint not null
);
create index market_orders_country_idx on runtime.market_orders(country, created_at);

create table runtime.market_participants (
  id text primary key, order_id text not null, user_id text not null,
  role text not null, seller_id integer not null default 0
);
create index market_participants_user_idx on runtime.market_participants(user_id, order_id);
create index market_participants_order_idx on runtime.market_participants(order_id);

create table runtime.market_products (
  key text primary key, country text not null, product_id integer not null,
  seller_id integer not null, owner_user_id text not null, data text not null,
  stock integer not null, revision integer not null default 1, updated_at bigint not null
);
create index market_products_country_idx on runtime.market_products(country);
create index market_products_owner_idx on runtime.market_products(owner_user_id);

create table runtime.account_identifiers (
  id bigint generated by default as identity primary key,
  user_id text not null, role text not null, unique(user_id, role)
);

create table runtime.auth_users (
  id text primary key, login text unique not null,
  password_hash text not null, created_at bigint not null
);
create table runtime.auth_sessions (
  token_hash text primary key, user_id text not null references runtime.auth_users(id) on delete cascade,
  expires_at bigint not null, issued_at bigint not null default 0, mfa_generation text
);
create index auth_sessions_expiry on runtime.auth_sessions(expires_at);
create table runtime.auth_limits (
  key text primary key, count integer not null, expires_at bigint not null
);
create table runtime.private_files (
  key text primary key, body bytea not null, content_type text not null
);
create table runtime.google_identities (
  subject text primary key, user_id text not null references runtime.auth_users(id) on delete cascade
);
create table runtime.google_states (
  state_hash text primary key, verifier text not null, nonce text not null,
  return_path text not null, expires_at bigint not null
);
create table runtime.auth_mfa (
  user_id text primary key references runtime.auth_users(id) on delete cascade,
  generation text not null, secret_cipher text not null, enabled integer not null default 0,
  pending_expires bigint not null, last_step bigint not null default -1
);
create table runtime.auth_mfa_recovery (
  user_id text not null references runtime.auth_users(id) on delete cascade,
  code_hash text not null, primary key(user_id, code_hash)
);
create table runtime.auth_mfa_challenges (
  token_hash text primary key, user_id text not null references runtime.auth_users(id) on delete cascade,
  generation text not null, expires_at bigint not null, attempts integer not null default 0
);
create index auth_mfa_challenge_expiry on runtime.auth_mfa_challenges(expires_at);

create table runtime.product_view_events (
  country text not null, product_id integer not null, visitor_hash text not null,
  bucket bigint not null, viewed_at bigint not null,
  primary key(country, product_id, visitor_hash, bucket)
);
create index product_view_period_idx on runtime.product_view_events(country, product_id, viewed_at);

grant select, insert, update, delete on all tables in schema runtime to yaviya_runtime;
grant usage, select on all sequences in schema runtime to yaviya_runtime;
grant execute on function runtime.json_extract(text, text) to yaviya_runtime;
alter default privileges in schema runtime
  grant select, insert, update, delete on tables to yaviya_runtime;
alter default privileges in schema runtime grant usage, select on sequences to yaviya_runtime;

-- Guard against accidental browser/Data API access even if exposed schemas change.
revoke all on all tables in schema runtime from public, anon, authenticated;
revoke all on all sequences in schema runtime from public, anon, authenticated;
